/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa.usuario;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Omar Castillo
 */
public class frmAdministrador extends javax.swing.JFrame {

    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo properties", "properties");
    public frmAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreArchivo = new javax.swing.JLabel();
        txtNombreArchivo = new javax.swing.JTextField();
        lblRutaArchivo = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        itmAbrir = new javax.swing.JMenuItem();
        itmSalir = new javax.swing.JMenuItem();
        mnuHerramientas = new javax.swing.JMenu();
        mnuAdministrador = new javax.swing.JMenu();
        itmUsuario = new javax.swing.JMenuItem();
        mnuGestionar = new javax.swing.JMenu();
        itmDispositivos = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        itmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreArchivo.setText("Nombre de Archivo:");
        getContentPane().add(lblNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(txtNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 30));

        lblRutaArchivo.setText("Ruta de Archivo:");
        getContentPane().add(lblRutaArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });
        getContentPane().add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 30));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 190));

        mnuBar.setToolTipText("");

        mnuArchivo.setText("Archivo");

        itmAbrir.setText("Arbir");
        itmAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAbrirActionPerformed(evt);
            }
        });
        mnuArchivo.add(itmAbrir);

        itmSalir.setText("Salir");
        itmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(itmSalir);

        mnuBar.add(mnuArchivo);

        mnuHerramientas.setText("Herramientas");

        mnuAdministrador.setText("Administrador");

        itmUsuario.setText("Usuario");
        mnuAdministrador.add(itmUsuario);

        mnuHerramientas.add(mnuAdministrador);

        mnuGestionar.setText("Gestionar");

        itmDispositivos.setText("Dispositivos");
        itmDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDispositivosActionPerformed(evt);
            }
        });
        mnuGestionar.add(itmDispositivos);

        mnuHerramientas.add(mnuGestionar);

        mnuBar.add(mnuHerramientas);

        mnuAyuda.setText("Ayuda");

        itmAcerca.setText("Acerca de...");
        mnuAyuda.add(itmAcerca);

        mnuBar.add(mnuAyuda);

        setJMenuBar(mnuBar);
        mnuBar.getAccessibleContext().setAccessibleName("Administrador");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaActionPerformed

    private void itmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmSalirActionPerformed

    private void itmAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAbrirActionPerformed
        JFileChooser seleccionaArchivo = new JFileChooser();
        seleccionaArchivo.setFileFilter(filter);
        int resultado = seleccionaArchivo.showOpenDialog(this);
        if(resultado == JFileChooser.APPROVE_OPTION){
            String nombreArchivo = seleccionaArchivo.getSelectedFile().getName();
            String ruta = seleccionaArchivo.getSelectedFile().getPath();
            txtNombreArchivo.setText(nombreArchivo);
            txtRuta.setText(ruta);
        }
    }//GEN-LAST:event_itmAbrirActionPerformed

    private void itmDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDispositivosActionPerformed
        frmGestionarDispositivos vNuevoDevice = new frmGestionarDispositivos();
        vNuevoDevice.setVisible(true);
        dispose();
    }//GEN-LAST:event_itmDispositivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAbrir;
    private javax.swing.JMenuItem itmAcerca;
    private javax.swing.JMenuItem itmDispositivos;
    private javax.swing.JMenuItem itmSalir;
    private javax.swing.JMenuItem itmUsuario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreArchivo;
    private javax.swing.JLabel lblRutaArchivo;
    private javax.swing.JMenu mnuAdministrador;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuGestionar;
    private javax.swing.JMenu mnuHerramientas;
    private javax.swing.JTextField txtNombreArchivo;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
